ifeq ($(OCAMLC),)
OCAMLC=ocamlc
endif

ifeq ($(OCAMLOPT),)
OCAMLOPT=ocamlopt
endif

ifeq ($(OCAMLDEP),)
OCAMLDEP=ocamldep
endif

ifeq ($(PREFIX),)
DESTDIR=$(shell ocamlfind printconf destdir)
PREFIX=$(shell dirname $(DESTDIR))
endif
